//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class custo
    {
        public string NIC { get; set; }
        public string cname { get; set; }
        public string phone_no { get; set; }
        public string check_in { get; set; }
        public string check_out { get; set; }
        public byte[] photo { get; set; }
    }
}
