//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string NIC { get; set; }
        public string Address { get; set; }
        public int Age { get; set; }
        public string PhoneNo { get; set; }
        public double Salary { get; set; }
    }
}
