//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string Item_code { get; set; }
        public string item_name { get; set; }
        public int Qty { get; set; }
        public double price { get; set; }
    }
}
