//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempOrder
    {
        public string item_name { get; set; }
        public double price { get; set; }
        public int qty { get; set; }
        public double tot { get; set; }
    }
}
